<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="J. Scott Cardinal">
<meta name="dcterms.date" content="2022-09-22">

<title>Bipartite Graphs for Archaeological Assemblage Networks (Part I)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="assemblage_network_doc_files/libs/clipboard/clipboard.min.js"></script>
<script src="assemblage_network_doc_files/libs/quarto-html/quarto.js"></script>
<script src="assemblage_network_doc_files/libs/quarto-html/popper.min.js"></script>
<script src="assemblage_network_doc_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assemblage_network_doc_files/libs/quarto-html/anchor.min.js"></script>
<link href="assemblage_network_doc_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assemblage_network_doc_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assemblage_network_doc_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assemblage_network_doc_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assemblage_network_doc_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bipartite Graphs for Archaeological Assemblage Networks (Part I)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>J. Scott Cardinal </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 22, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="archaeo_DS.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Indiana Jones and the Temple of Math?</figcaption><p></p>
</figure>
</div>
<p>I’ve occasionally been asked, especially since I decided to go “all in” by getting another graduate degree<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, what data science has to do with <em>archaeology</em>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> This will be the first of a short series of articles to demonstrate how I’ve been using data, statistics, and such to gain insights into what is a surprisingly convoluted area of research. Basically, while many data scientists are trying to make inferences about the present or future I’ve been finding ways to apply those same methods to understanding the past.</p>
<p>Although I’m using an archaeological example, the methods presented here can be used for any number of research questions in other fields. I’ll be covering some basics of:</p>
<ul>
<li><p>Part I – Creating and exploring bipartite and one-mode graphs</p></li>
<li><p>Part II – Similarity measures for sets and graph adjacency,</p></li>
<li><p>Part III – Graph structure and community detection methods,</p></li>
<li><p>Part IV – Geo-spatial networks</p></li>
</ul>
<p>I’ll be using R for the coding, but all of this could be done in Python just as easily.</p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>An archaeological site consists, in essence, of a discretely-bounded spatial area of interrelated artifact deposits and features.</p>
<p>Less formally – it’s <em>old stuff</em> scattered across a <em>place</em> where <em>someone</em> did <em>something</em>. It’s a big jigsaw puzzle in many ways. Imagine that you had a photograph (a physical one, not one of those newfangled digital thingies). You don’t know who is in the photograph or quite what they’re doing in it.</p>
<p>Now imagine that someone had torn that photo into hundreds or thousands of irregular pieces…</p>
<ul>
<li><p><em>then threw away at least half of them…</em></p></li>
<li><p><em>then scattered the remaining pieces across an open field exposed to the elements…</em></p></li>
<li><p><em>which was then trod on for a few centuries by various livestock, people, and critters…</em></p></li>
<li><p><em>and someone later comes along and builds their new house or road or parking lot on top of them!</em></p></li>
</ul>
<p>What would be left over from all of that would pretty be much the data that we poor archaeologists have left over to make sense of that picture.</p>
<p>The job of the archaeologist is to find patterns within those data that make sense of what happened in that location over time. We want to find out what that <em>something</em> was that they were doing, which often tells us a bit about just who those <em>someones</em> in the past were. We do this by digging very precisely controlled sample excavations across the area of a site, and then try and infer the overall spatial distributions of different sorts of artifacts from those samples.</p>
<section id="the-structure-of-archaeological-data" class="level3">
<h3 class="anchored" data-anchor-id="the-structure-of-archaeological-data">The Structure of Archaeological Data</h3>
<p>As an archaeologist and a data scientist (in no specific order), my job is to take the data from those excavated samples and see if I can find – and quantify – those patterns.</p>
<p>So, the first part of trying to do all that is to see whether or not there is a pattern to what <em>stuff</em> is found together and which <em>places</em> contain the most similar <em>stuff</em> in them.</p>
<p>More formally, we are trying to find subsets within a system of sets consisting of a set of locations and a set or artifacts. I wrote an article a few years ago <span class="citation" data-cites="cardinal2019">(<a href="#ref-cardinal2019" role="doc-biblioref">Cardinal 2019</a>)</span>, which went into great detail about the nature of that <em>place</em>-<em>thing</em> system of sets. It all boils down to something that looks rather like this:</p>
<p><span class="math display">\[
\begin{aligned}
  \left(\mathcal{A}_i,\mathcal{C}_i\right) =  \left\{\vphantom{\biguplus_{i}^n}\right.{} &amp;\left.{}\exists \mathcal{X}_i \in^{m(x)} \wp(\mathcal{S}) - \emptyset, \right.{}\\
  &amp;\left.{}\exists \mathcal{Y}_i \in^{m(y)} \wp(\mathbb{V}) - \emptyset \right.{}\\
  &amp;\left.{} \mid\mathcal{X}_i \approx \biguplus_{j=1}^n \mathcal{V}_j \in^{m(y)} \mathcal{Y}_i\right\}
\end{aligned}
\]</span></p>
<p>Not overly user-friendly, I’ll admit. Trust me, it makes sense (eventually) if you read my article?</p>
<p>In graph terminology, what we’re looking for are either discrete sub-graphs or communities (i.e., induced sub-graphs or “cliques”) across two graphs simultaneously – one of places and one of artifact types. In other words, a two-mode (or “bipartite”) graph.</p>
<p>For those unfamiliar, a two-mode graph is one in which there are two mutually exclusive <em>types</em> of vertices (i.e., nodes) and edges can <em>only</em> exist between vertices of different types. In this case, we have <em>places</em> and we have <em>things</em>.</p>
<p>For now, we only want to know which <em>things</em> most often occur in the same <em>place</em> and which <em>places</em> contain similar <em>things</em>. The <em>observable</em> relationships between artifacts are indicated by their co-locations (i.e., presence within the same proveniences). In the broader sense, though the goal is to look at <em>why</em> those artifact turn up together – are they from the same time period, do they reflect a specific type of activity, are they from one or more households, et cetera. The answers to those questions aren’t observable, but locations and co-locations of artifacts are.</p>
<p>The data used in the following example is from an <em>actual</em> archaeological site (a collection of household structures, occupied circa mid-18th to 20th century) and not a toy example or simulated data. As such, it is as <em>messy</em> as real-world data tends to be – the groups of artifacts and proveniences do <em>not</em> cleanly cluster or sort out into neat divisions, but (spoiler alert!) there really are clusters present both in spatial organization and assemblages. We’ll be walking through a part of the process that I used to find and evaluate those sorts of patterns.</p>
</section>
</section>
<section id="making-a-bipartite-graph-in-r" class="level2">
<h2 class="anchored" data-anchor-id="making-a-bipartite-graph-in-r">Making a Bipartite Graph in R</h2>
<p>We can create a bipartite graph quite easily with the package <code>igraph</code>, although it doesn’t really have much in the way of methods for analyzing two-mode graphs directly. For our purposes, that isn’t much of a problem as we’re mainly interested using it as a way to get at each one-mode graph (i.e., <em>places</em> and <em>things</em> separately).</p>
<p>The packages we’ll be using are <code>igraph</code> (to create, manipulate, and analyze the graphs), <code>tidyverse</code> for data frame management, and <code>ggraph</code> for visualizations. There are, of course, other packages that could work as well. These are just the ones I’ve been accustomed to using.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(igraph)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(ggraph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To start we’ll import the data from our text file, which is the database of the artifact catalog. In it is listed details about each artifact type that was found at each of the locations (called a “provenience”). We don’t really need the details about each artifact type for now as we’re only looking for the associations, so we only really need two fields – the provenience (<code>LEVEL_ID</code>) and the artifact type code (<code>CODE</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Catalog_SiteA.csv"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">col_select =</span> <span class="fu">c</span>(LEVEL_ID, CODE)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next we create our two-mode un-directed graph (<code>assemblages_bpg</code>) with <code>graph_from_data_frame</code> using <em>unique</em> pairs of <code>LEVEL_ID</code> and <code>CODE</code> in the data frame <code>dat</code>.</p>
<p>It’s an <em>un-directed</em> graph since there isn’t any real meaning to an ordering or hierarchy of the vertices. The relationship is bi-directional – a <em>place</em> contains <em>things</em>, and the <em>things</em> are equivalently found in that <em>place</em>. To keep things simple, we’ll be creating an <em>un-</em>weighted bipartite graph that ignores multiplicity (i.e., how <em>many</em> of each artifact type is found at each provenience). For now, we’re only going to look at co-presence or co-location of types.</p>
<p>Then we use the method <code>bipartite_mapping</code> to assign type to the vertices based on which of the two columns the node is from.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>g_assemblages_bpg <span class="ot">&lt;-</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">graph_from_data_frame</span>(<span class="fu">unique.data.frame</span>(dat),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">directed =</span> <span class="cn">FALSE</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                        )</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(g_assemblages_bpg)<span class="sc">$</span>type <span class="ot">&lt;-</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bipartite_mapping</span>(g_assemblages_bpg)<span class="sc">$</span>type</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>g_assemblages_bpg <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggraph</span>(<span class="at">layout =</span> <span class="st">"bipartite"</span>) <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link</span>(<span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> type), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"green"</span>, <span class="st">"blue"</span>),</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"Node Type"</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>, <span class="cn">TRUE</span>),</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Provenience"</span>, <span class="st">"Artifact"</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assemblage_network_doc_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="768"></p>
<p></p><figcaption class="figure-caption">Bipartite graph of artifact-provenience connections.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Now we have our graph of connections between artifact types and locations, and can already see some rough grouping in each of the vertex types (one type at the top and one at the bottom of the plot). The graph is densely connected, with many nodes and edges.</p>
<p>Lets take a quick look at the bipartite <code>igraph</code> object itself:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>g_assemblages_bpg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IGRAPH 61efd81 UN-B 403 2533 -- 
+ attr: name (v/c), type (v/l)
+ edges from 61efd81 (vertex names):
 [1] 1726--UDB  1725--UDB  1726--TOOT 1725--TOOT 1726--CS   1725--OCH 
 [7] 1726--BNUT 1726--UIS  1725--UIS  1725--TWN  1726--UWN  1726--MCN 
[13] 1725--MCN  1725--UCN  1726--UCN  1726--CWN  1726--BLT  1725--CAP 
[19] 1726--SCR  1725--TACK 1726--TACK 1726--WAS  1725--CF   1725--OPOP
[25] 1726--AXE  1726--STOL 1726--ODMT 1726--UTI  1726--XI   1725--XI  
[31] 1726--XSV  1725--XSV  1726--OBS  1725--OTSW 1726--OTSW 1726--XY  
[37] 1726--OBR  1726--AFG  1725--AFG  1726--CFG  1726--GB   1726--CPTG
[43] 1726--CTG  1726--CCG  1725--CCG  1726--CVCG 1726--ABG  1725--CBG 
+ ... omitted several edges</code></pre>
</div>
</div>
<p>The text at the top <code>IGRAPH 2ea26e5 UN-B 403 2533 --</code> tells us that it’s un-directed (<code>U</code>), nodes have a <code>name</code> attribute (<code>N</code>), is un-weighted (<code>-</code>), and is a bipartite graph (<code>B</code>) that has 403 vertices and 2,533 edges. In the listed preview of edges, you’ll see number and text pairs (e.g., <code>1726--UDB</code>) that are combinations of the numerical provenience (<code>LEVEL_ID</code>) and textual artifact type code (<code>CODE</code>).</p>
<p>We can easily retrieve the incidence matrix with (shock!) the method <code>as_incidence_matrix</code> and take a peek of the first few rows and columns…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>assemblages_inc <span class="ot">&lt;-</span> <span class="fu">as_incidence_matrix</span>(g_assemblages_bpg)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>assemblages_inc[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     UDB TOOT CS OCH BNUT UIS TWN UWN MCN UCN CWN BLT CAP SCR TACK
1726   1    1  1   0    1   1   0   1   1   1   1   1   0   1    1
1725   1    1  0   1    0   1   1   0   1   1   0   0   1   0    1
1306   0    0  0   1    0   1   0   1   1   1   1   0   0   0    1
1307   0    0  0   1    0   1   0   0   0   0   1   0   0   0    0
1737   1    0  0   0    1   1   0   0   1   1   1   1   0   1    0</code></pre>
</div>
</div>
<p>It’s simply a binary two-mode contingency or two-mode adjacency table showing the presence (<code>1</code>) or absence (<code>0</code>) of an artifact type at each location.</p>
<section id="projecting-each-mode-for-analysis" class="level3">
<h3 class="anchored" data-anchor-id="projecting-each-mode-for-analysis">Projecting each mode for analysis</h3>
<p>Analyzing bipartite graph metrics directly is somewhat complicated, since the most common metrics for graphs (e.g., centrality measures, etc.) are skewed by the inclusion of both types of vertices and the dependencies between them. What can do more easily is project a <em>weighted</em> graph of each mode, and then analyze those.</p>
<p>Again, <code>igraph</code> makes this easy. We use the method <code>bipartite_projection</code> with the setting <code>multiplicity = TRUE</code> in order to create weighted graph projections for each mode. Since our goal is to associate proveniences that have the <em>most</em> commonality of artifact types and types that show up most often together, we need those multiplicities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>assemblage_projections <span class="ot">&lt;-</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bipartite_projection</span>(g_assemblages_bpg, <span class="at">multiplicity =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>assemblage_projections</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$proj1
IGRAPH 709165c UNW- 152 9817 -- 
+ attr: name (v/c), weight (e/n)
+ edges from 709165c (vertex names):
 [1] 1726--1725 1726--1737 1726--1738 1726--1744 1726--1746 1726--1730
 [7] 1726--1727 1726--1760 1726--1765 1726--1761 1726--1769 1726--1826
[13] 1726--1822 1726--1794 1726--1807 1726--1836 1726--896  1726--899 
[19] 1726--1763 1726--1745 1726--1747 1726--1750 1726--1755 1726--1753
[25] 1726--1754 1726--1756 1726--1752 1726--1757 1726--1758 1726--1762
[31] 1726--1815 1726--1816 1726--1779 1726--1780 1726--1778 1726--1797
[37] 1726--1799 1726--1806 1726--1805 1726--1804 1726--1829 1726--1830
[43] 1726--1837 1726--1838 1726--1839 1726--1841 1726--1842 1726--888 
+ ... omitted several edges

$proj2
IGRAPH 709168b UNW- 251 9494 -- 
+ attr: name (v/c), weight (e/n)
+ edges from 709168b (vertex names):
 [1] UDB--TOOT UDB--CS   UDB--BNUT UDB--UIS  UDB--UWN  UDB--MCN  UDB--UCN 
 [8] UDB--CWN  UDB--BLT  UDB--SCR  UDB--TACK UDB--WAS  UDB--AXE  UDB--STOL
[15] UDB--ODMT UDB--UTI  UDB--XI   UDB--XSV  UDB--OBS  UDB--OTSW UDB--XY  
[22] UDB--OBR  UDB--AFG  UDB--CFG  UDB--GB   UDB--CPTG UDB--CTG  UDB--CCG 
[29] UDB--CVCG UDB--ABG  UDB--CBG  UDB--GBG  UDB--MBG  UDB--NBG  UDB--OBG 
[36] UDB--FOSS UDB--OCI  UDB--OCO  UDB--OSL  UDB--TARP UDB--OCH  UDB--TWN 
[43] UDB--CAP  UDB--CF   UDB--OPOP UDB--ORUB UDB--BIF  UDB--RN   UDB--URN 
[50] UDB--UN   UDB--ALUM UDB--UNZ  UDB--ACG  UDB--MLCG UDB--CVBG UDB--WOOD
+ ... omitted several edges</code></pre>
</div>
</div>
<p>You’ll see that we now have the two one-mode graphs as <code>$proj1</code> for proveniences and <code>$proj2</code> for artifact types. All that is left is to assign these projections to their own individual one-mode graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>g_assemblage_prov <span class="ot">&lt;-</span> assemblage_projections<span class="sc">$</span>proj1</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>g_assemblage_artifact <span class="ot">&lt;-</span> assemblage_projections<span class="sc">$</span>proj2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a look at the resulting graph projections.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>g_assemblage_prov <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggraph</span>(<span class="at">layout =</span> <span class="st">"fr"</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link</span>(<span class="fu">aes</span>(<span class="at">alpha =</span> weight)) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>(<span class="at">color =</span> <span class="st">"green"</span>, <span class="at">size =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assemblage_network_doc_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Projected graph of provenience.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>g_assemblage_artifact <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggraph</span>(<span class="at">layout =</span> <span class="st">"fr"</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link</span>(<span class="fu">aes</span>(<span class="at">alpha =</span> weight)) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assemblage_network_doc_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Projected graph of artifact types.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Both graphs are obviously quite dense, and at this point it’s somewhat hard to tell if there are any patterns or communities within them. We’ll need to explore them a bit to find out what all of those connections are telling us.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Now that we have our two one-mode graphs projected, you may be wondering – <em>why go through the trouble of making a bipartite graph in the first place</em>? There are a couple of reasons.</p>
<p>The first is that the relationships and associations we’re looking for are specifically the interactions <em>between</em> the two entities. Conceptually, that should make a certain sense. The archaeologically <em>observable</em> associations between artifact types are primarily by co-location. Similarly, proveniences are associated because they contain similar artifact types. These associations are themselves bipartite in nature, so by initializing our graphs <em>by</em> that relationship is simply the correct way to address them.</p>
<p>Secondly, it’s just an <em>elegant</em> way to go about it. We could, of course, have gone about building the individual graphs from the source data table by building pivot and contingency tables then converting those into adjacency matrices and graphs. By building it this way, however, we collapsed a whole bunch of steps and built both of our graphs with a few of lines of really straightforward code! As an added benefit, we can just as easily pull out those individual contingency tables and such just like we did with the incidence matrix at the start. Why make extra work?</p>
</div>
</div>
</section>
</section>
<section id="analyzing-the-projected-graphs" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-the-projected-graphs">Analyzing the Projected Graphs</h2>
<p>If you noticed above, both of our one-mode graphs are quite dense. For example, the provenience graph <code>G_assemblage_prov</code> has 9,817 edges but only 152 vertices? The maximum number of edges possible in an un-directed graph is <span class="math inline">\(\frac{1}{2} \times |V| \times (|V|-1)\)</span>, so with 152 vertices the most possible edges is 11,476 and our graph has a density of ~86%.</p>
<p>We’ll start by looking at the density distribution of the <em>degrees</em> of our vertices, or how many other vertices each one is connected to.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(<span class="fu">degree</span>(g_assemblage_prov)), <span class="at">col =</span> <span class="st">"green"</span>,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of Provenience Degree"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assemblage_network_doc_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We see from the left-skew of the distribution that most of the vertices are actually connected to most of the other vertices. If that’s true, then there really wouldn’t be any differentiation to be made between proveniences (i.e., no community structure) and the 86% density just indicates a relatively homogeneous site.</p>
<p>Now, let’s look at the distribution of weights for those edges.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(<span class="fu">E</span>(g_assemblage_prov)<span class="sc">$</span>weight, <span class="at">bw =</span> <span class="dv">1</span>), <span class="at">col =</span> <span class="st">"green"</span>,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of Provenience Edge Weights"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assemblage_network_doc_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we see the opposite – the distribution is right-skewed, meaning that the vast majority of our edges are being formed by <em>weak</em> similarities (i.e., having only a small number artifacts in common).</p>
<p>So now we know <em>why</em> our provenience graph is so dense – if it only takes one or more artifacts in common to connect two locations, and most proveniences have at least one in common, then everything is pretty well connected.</p>
<p>Maybe certain artifact types are just showing up in many places? We need to find a way to thin out the graph such that only the really <em>meaningful</em> connections form edges.</p>
<p>Let’s look at our artifact graph <code>G_assemblage_artifact</code> next. It’s not <em>quite</em> as dense (251 vertices, 9,494 edges out of a possible 31,375, so ~30%), but we’ll again look at vertex degree and edge weight densities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(<span class="fu">degree</span>(g_assemblage_artifact)), <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of Artifact Degree"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assemblage_network_doc_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we see a <em>somewhat</em> right-skewed degree density distribution, but most are rather strongly connected (~50+ connections) and notice the “bumps” toward the right tail – it seems that at least some of our artifact types <em>do</em> show up alongside most others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(<span class="fu">E</span>(g_assemblage_artifact)<span class="sc">$</span>weight, <span class="at">bw =</span> <span class="dv">1</span>), <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of Artifact Edge Weights"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assemblage_network_doc_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The artifact edge weights are <em>heavily</em> right-skewed, and notice just how <em>far</em> that right tail extends. What that is telling us is that some, but not many, of the artifact types are showing up in a lot of locations. Most artifact types are only co-located in a fairly few (~3-4) proveniences, though.</p>
<section id="interpretation-of-degree-and-edge-weights" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-degree-and-edge-weights">Interpretation of degree and edge weights</h3>
<p>We now have a rough idea of what is going on in our system of <em>place</em>-<em>thing</em> sets:</p>
<ul>
<li><p>Both of the individual projection graphs are dense, but most of those connections are weak.</p></li>
<li><p>It seems likely that a relatively small number items in each set are generating those weak connections. Certain artifacts show up in a large number of provenience, and some provenience contain a large and diverse set of artifact types.</p></li>
<li><p>These weak-but-dense connections may be masking or overwhelming the underlying structure in the graphs.</p></li>
</ul>
<p>What we need to do next is to find a way to distinguish between <em>informative</em> connections and <em>spurious</em> connections.</p>
</section>
</section>
<section id="the-next-steps" class="level2">
<h2 class="anchored" data-anchor-id="the-next-steps">The Next Steps…</h2>
<p>One might think that the obvious next step would be to simply start removing the weakest edges, and in some cases that would be the way to go. Remember, though, that our goal is actually to analyze the <em>relationships</em> (i.e., the connecting edges) between artifacts and locations. The strength of individual vertices aren’t the objective, but rather we want to identify <em>communities</em> of vertices derived from their relationships.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>What’s happened is that the method we’ve used to project the one-mode graphs is simply tabulating the number of times an individual provenience and artifact type coincides. The problem is that one shared artifact can connect locations, and one shared location connects artifacts. That’s not quite what we’re after. We want to link vertices that have the most similar <em>collections</em> or <em>profiles</em> of co-occurrence. In other words, we need to look at both the intersections of the sets <em>and</em> their differences to ascertain similarities.</p>
<p>For that, we need a different method of projection. In the next installment, we’ll look at some set-based measures of similarity and see what happens when we project our one-mode graphs that way.</p>

</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-cardinal2019" class="csl-entry" role="doc-biblioentry">
Cardinal, J. Scott. 2019. <span>“Sets, Graphs, and Things We Can See: A Formal Combinatorial Ontology for Empirical Intra-Site Analysis.”</span> <em>Journal of Computer Applications in Archaeology</em> 2 (1): 56–78. <a href="https://doi.org/10.5334/jcaa.16">https://doi.org/10.5334/jcaa.16</a>.
</div>
</div></section><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>Georgia Institute of Technology Master of Science in Analytics from the College of Computing, Scheller College of Business, and College of Engineering. I highly recommend the program!<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>I’m also sometimes asked the inverse – what does archaeology have to do with <em>data science</em> – by my archaeological colleagues as well. Quantitative and computational (or “digital”) archaeology has been around for a long while, but we’re still something of a minority. That’s a subject for a different post, though.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>Readers versed in graph theory may already notice that we’re ultimately aiming for edge betweenness and centrality metrics.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>